---
title: "Analyzing Sustainability Indicators Amidst Climate Change"
author: 
- "Eglah Belizor"
- "Shamil Khusnullin"
- "Mariia Koval"
abstract: "We analyze global trends in sustainability from 1990 to 2022 in terms of CO₂ emissions, renewables usage, deforestation, and fossil fuel usage. Through visualization, clustering, and logistic regression, we uncover clusters of nations by sustainability levels and how they shift over time. Europe and North America reduced emissions, while Southeast Asia grew tremendously. Growth in renewable energy and a reduction in fossil fuel usage were strong predictors of enhanced sustainability."

resources:
      - Data/co2_map.rds`

filters:
  - shinylive
  
---

# Summary of policies

As discussed in the earlier sections, there is a variety of indicators that change on a country to country basis and have different implications for the climate change, sustainable development, and environmental crisis mitigation. Organizations, such as United Nations, International Energy Agency, World Bank, OECD, among others, prepare reports with annual changes in countries' policy frameworks and sustainability indicators. To compare the strategies of these countries and assess the effectiveness of actions they implement, we outlined the most insightful strategies. Data-driven approach in policy-making is crucial to establishing associations and causality among many factors.

[The Emissions Gap Report 2024](https://www.unep.org/resources/emissions-gap-report-2024) provided by UNEP underscores the urgency in combating greenhouse gas emissions (GHG) and control the project rise in global temperatures. For instance, according to the Paris Agreement, the world is determined to achieve the goal of limiting global warming to 1.5°C. In order to reach this objective, GHG emissions have to be decreased by 42% by 2030, and by 57% by 2035. Based on current projections, the temperatures are on track to rise to 2.6-3.1°C by the nend of the century.</p>

G20 countries are collectively responsible for 77% of global emissions, so they are at the front lines of shaping global climate changes. The report emphasizes the need for more aggressive and consistent policies implemented by these countries to mitigate air pollution. There are also Nationally Determined Contributions (NDCs), which are environmental targets set by individual countries. In fact, by 2023, 80% of countries set emission reduction targets for 2030, with 55% covering all industries and 58% addressing key pollutants like carbon dioxide, methane, and nitrous oxide. Here is an example of policies and analysis on a country-to-country basis:

* While China has made significant investment in renewable energy, it hasn’t been successful in achieving its emission reduction targets.
* The United States has also implemented measures to combat rising temperatures, but they are insufficient to meet the 1.5°C target. Strengthening them further can have co-benefit for air pollution challenges.
* India has implemented the National Action Plan on Climate Change (NAPCC), focusing on areas like solar energy, energy efficiency, and sustainable habitats. The Action Plan aims to achieve net zero emissions by 2070, increase non-fossil fuel capacity to 500 GW and meet 50% of energy needs from renewable sources by 2030.

Further policy recommendations include strengthening NDCs to apply an individualized approach focused on challenges within specific region, based on available funding, resources, and risks. UNEP calls upon other countries to establish more precise monitoring systems to detect and adress air pollution sources promptly. An example of such initiative is [Methane Alert and Response System (MARS)](https://www.unep.org/topics/energy/methane/international-methane-emissions-observatory/methane-alert-and-response-system) which is the first global satellite detection and notification system providing actionable data on large methane emissions around the world. Transitioning to clean renewable energy is emphasized as a way to target both air pollution and GHG emissions. Therefore, both funds and technologies have to be established and shared in developed and developing countries to facilitate global holistic change.

# Green Energy

Rapidly worsening climate change and policymakers’ efforts have pushed countries around the world to switch to clean energy. Following the COVID-2019 pandemic, almost 150 countries that make up 95% of greenhouse gas emissions have agreed on setting new ambitious targets on energy efficiency. 15 countries of the G20 now follow the regulations to track their energy performance in key energy sectors like power and industry. These changes have positively impacted 70% of their sector emissions. 

In the inaugural edition of the [IEA (2024)](https://www.iea.org/reports/state-of-energy-policy-2024/key-findings), the article claims that countries have made over 2 trillion in direct investments in the renewable energy sector, presenting a triplefold increase from investments that followed the 2008 financial crisis. While 80% of these investments come directly from three regions–China, the European Union, and the US– more than 40 other countries have made investments totaling $290 billion in the first half of 2024. 

In the past years, 10% of total government spending accounts for domestic clean energy suppliers. For example, the EU’s Net Zero Industry Act sets domestic manufacturing targets for clean tech and includes permitting processes to accelerate deployment. The U.S. Defence Production Act has also shown initiatives to boost domestic output of critical minerals and battery components. 

However, there are still some significant challenges remaining. 80% of the main clean energy manufacturing capacity is concentrated within the top 3 countries. This fact implies that the clean energy sector chain is vulnerable to trade wars, policy changes within the country, and other unseen geopolitical swings.



## Bibliography

Additional information used:

* [Methane Alert and Response System (MARS)](https://www.unep.org/topics/energy/methane/international-methane-emissions-observatory/methane-alert-and-response-system) - A global initiative led by UNEP to detect and address major methane leaks in near real-time.</li>
* [The Emissions Gap Report 2024](https://www.unep.org/resources/emissions-gap-report-2024) - Annual report analyzing the gap between current climate pledges and the emissions reductions needed to meet global climate targets.</li>
* [How Halting Deforestation Helps Fight Climate Change](https://www.unep.org/news-and-stories/story/how-halting-deforestation-can-help-counter-climate-crisis) - UNEP article exploring the role of forest conservation in mitigating the climate crisis.</li>
* [Solar Energy’s Climate Impact: IPCC Report](https://www.ipcc.ch/site/assets/uploads/2018/03/Chapter-3-Direct-Solar-Energy-1.pdf) - Assessment of solar energy’s potential to reduce emissions, stating its impact can be 10,000 times more beneficial than fossil fuels.</li>

